### ISSUE TITLE
Restart site fails when the site hasn't yet been started

### ISSUE THREAD

**Issue by langdonx** [warrenbuckley/IIS-Express-Code#41]
It looks like the new updates caused an issue here.  If you open a fresh copy of VS Code and run the Restart command it fails.

Rather than fiddle with Start and Stop, I have always had Restart bound to F5 and used it exclusively without any issues.

```
[2018-06-07 09:23:13.580] [exthost1] [error] TypeError: Cannot read property 'restartSite' of undefined
	at vscode.commands.registerCommand (C:\Users\langdonx\.vscode\extensions\warren-buckley.iis-express-1.1.2\out\extension.js:66:16)
	at e._executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:674:613)
	at e.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:675:6)
	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:832)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:550)
	at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:631)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:400)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:634:315
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:637:395
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:95:432
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:764)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:338)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20) extension.iis-express.restart
```

**Comment by langdonx** [comment]
It looks like it was mentioned in a comment but not covered:

```
		//Open site in browser - this will need to check if site is running first...
		//Pass settings - just in case its changed between session (Hence not set globally in this file)
		iisProc.restartSite(settings.getSettings());
```

Not sure how you want to handle this, if at all since you can't exactly "Restart" something that hasn't been started.  Perhaps it's working as intended?  If anything it could use a better error/warning instead of throwing.  I'd recommend moving lines 18-26 into some sort of initialization method that gets run before any command is executed (maybe there's a hook in the extension api?)

As a work around, it appears that the Start action now behaves like Restart used to, so in the meantime I've bound that to F5.

**Comment by warrenbuckley** [comment]
Can confirm this has been fixed already
